const W = 1600, H = 900;
const COLORS = { ink:0x253257, purple:0x6d5dfc, violet:0x8c70ff, yellow:0xffd95a, mint:0x64d8b0, coral:0xff7c7c, sky:0x74d8ff, cream:0xfffbec, white:0xffffff, navy:0x29245d };
const restaurants = [
  {name:'Happy Burger', short:'Fast Food', icon:'🍔', color:0xff785f, badge:'Burger Star', clerk:'Mia', menu:[['Hamburger',60,'🍔'],['French Fries',45,'🍟'],['Hot Dog',50,'🌭'],['Chicken Nuggets',55,'🍗'],['Cola',30,'🥤'],['Ice Cream',40,'🍦']]},
  {name:'Sunny Breakfast', short:'Breakfast', icon:'🥞', color:0xffb84d, badge:'Morning Champ', clerk:'Ben', menu:[['Toast',35,'🍞'],['Hamburger',50,'🍔'],['Egg Pancake',45,'🥞'],['Milk Tea',30,'🧋'],['Coffee',40,'☕'],['Hash Brown',25,'🥔']]},
  {name:'Ocean Poke', short:'Poke Bowl', icon:'🥗', color:0x43cba5, badge:'Bowl Explorer', clerk:'Kai', menu:[['Salmon Bowl',180,'🍣'],['Tuna Bowl',170,'🐟'],['Chicken Bowl',150,'🍗'],['Edamame',40,'🫛'],['Miso Soup',35,'🍲'],['Green Tea',25,'🍵']]},
  {name:'Bubbly Tea', short:'Bubble Tea', icon:'🧋', color:0xb987ea, badge:'Bubble Wizard', clerk:'Lily', menu:[['Milk Tea',60,'🥛'],['Black Tea',40,'🫖'],['Green Tea',40,'🍵'],['Pearl Milk Tea',70,'🧋'],['Winter Melon Tea',50,'🍈'],['Lemon Tea',55,'🍋']]},
  {name:'Lucky Bento', short:'Chinese Bento', icon:'🍱', color:0xeb6666, badge:'Bento Hero', clerk:'Chen', menu:[['Chicken Bento',120,'🍱'],['Pork Bento',130,'🥩'],['Fish Bento',140,'🐟'],['Vegetable Bento',100,'🥬'],['Soup',30,'🍲'],['Tea',25,'🍵']]}
];
const levels=['Beginner','Food Explorer','Ordering Expert','Restaurant Master','Food Ordering Hero'];
const daily=['Order a drink','Practice a price','Visit a new restaurant','Say a full sentence','Review your badges'];

function loadSave(){try{return {...{completed:[],badges:[],xp:0},...JSON.parse(localStorage.getItem('aiRestaurantSave')||'{}')}}catch{return {completed:[],badges:[],xp:0}}}
function saveData(data){localStorage.setItem('aiRestaurantSave',JSON.stringify(data))}
function levelOf(save){return Math.min(5,save.completed.length+1)}
function t(scene,x,y,text,size=28,color='#253257',style={}){return scene.add.text(x,y,text,{fontFamily:'Nunito, Arial',fontSize:size,fontStyle:'bold',color,align:'center',...style}).setOrigin(.5)}
function panel(scene,x,y,w,h,fill=0xffffff,alpha=.95,r=24,stroke=0xffffff){const g=scene.add.graphics();g.fillStyle(fill,alpha).fillRoundedRect(x-w/2,y-h/2,w,h,r);g.lineStyle(4,stroke,.7).strokeRoundedRect(x-w/2,y-h/2,w,h,r);return g}
function button(scene,x,y,w,h,label,fill,onClick,icon=''){const c=scene.add.container(x,y);const shadow=scene.add.graphics().fillStyle(0x20204b,.24).fillRoundedRect(-w/2, -h/2+8,w,h,18);const bg=scene.add.graphics().fillStyle(fill,1).fillRoundedRect(-w/2,-h/2,w,h,18).lineStyle(3,0xffffff,.7).strokeRoundedRect(-w/2,-h/2,w,h,18);const tx=t(scene,0,-2,(icon?icon+'  ':'')+label,Math.min(25,h*.35),'#ffffff');c.add([shadow,bg,tx]).setSize(w,h).setInteractive({useHandCursor:true}).on('pointerup',()=>{sound('click');scene.tweens.add({targets:c,scale:.95,yoyo:true,duration:70});onClick?.()}).on('pointerover',()=>scene.tweens.add({targets:c,scale:1.04,duration:100})).on('pointerout',()=>scene.tweens.add({targets:c,scale:1,duration:100}));return c}
function sound(type='click'){try{const A=window.AudioContext||window.webkitAudioContext;window._ctx=window._ctx||new A();const c=window._ctx,o=c.createOscillator(),g=c.createGain();o.connect(g);g.connect(c.destination);const f={click:420,correct:660,badge:880,level:740,wrong:180}[type]||420;o.frequency.setValueAtTime(f,c.currentTime);if(type==='badge')o.frequency.exponentialRampToValueAtTime(1320,c.currentTime+.35);g.gain.setValueAtTime(.12,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+(type==='click'?.12:.45));o.start();o.stop(c.currentTime+(type==='click'?.12:.45))}catch{}}
function transition(scene,key,data){scene.cameras.main.fadeOut(260,45,38,100);scene.time.delayedCall(270,()=>scene.scene.start(key,data))}
function makeYummy(scene,x,y,scale=1){const c=scene.add.container(x,y).setScale(scale);const shadow=scene.add.ellipse(0,128,145,30,0x29365a,.22);const body=scene.add.graphics();body.fillStyle(0xffd05b).fillRoundedRect(-76,-55,152,170,65);body.fillStyle(0xffed9b).fillCircle(0,-65,92);body.fillStyle(0xffffff).fillCircle(-31,-74,25).fillCircle(31,-74,25);body.fillStyle(COLORS.ink).fillCircle(-25,-70,10).fillCircle(25,-70,10);body.lineStyle(8,COLORS.ink).beginPath().arc(0,-45,28,.15,Math.PI-.15).strokePath();body.fillStyle(0xffffff).fillRoundedRect(-62,20,124,76,24);body.fillStyle(0xff6f76).fillTriangle(-25,20,25,20,0,50);body.fillStyle(0xffffff).fillCircle(-88,35,24).fillCircle(88,35,24);body.fillStyle(0xff784e).fillRoundedRect(-62,-152,124,48,20);body.fillStyle(0xffffff).fillRoundedRect(-43,-178,86,38,18);c.add([shadow,body]);scene.tweens.add({targets:c,y:y-10,duration:1200,yoyo:true,repeat:-1,ease:'Sine.inOut'});return c}
function header(scene,title,subtitle=''){panel(scene,800,58,1540,92,0x272451,.9,28,0xffffff);t(scene,70,45,'AI RESTAURANT ADVENTURE',25,'#ffd95a',{fontStyle:'900'}).setOrigin(0,.5);t(scene,800,43,title,36,'#ffffff');if(subtitle)t(scene,800,76,subtitle,16,'#dcd9ff')}
function bottomNav(scene,active='home'){panel(scene,800,855,900,72,0xffffff,.96,24,0xe6e8ff);[['home','⌂','Home','Home'],['map','🗺','Map','Map'],['badges','🏅','Badges','Achievements'],['rank','🏆','Rank','Leaderboard']].forEach(([id,ic,label,key],i)=>{const x=505+i*195;const col=id===active?'#6d5dfc':'#68708c';const it=t(scene,x,842,ic+'  '+label,20,col).setInteractive({useHandCursor:true});it.on('pointerdown',()=>transition(scene,key))})}

class Boot extends Phaser.Scene{constructor(){super('Boot')}preload(){this.load.image('town','assets/food-town.png')}create(){this.scene.start('Home')}}
class Base extends Phaser.Scene{create(){this.save=loadSave();this.cameras.main.fadeIn(300);}}
class Home extends Base{constructor(){super('Home')}create(){super.create();this.add.image(800,450,'town').setDisplaySize(W,H).setTint(0xbfd8ff);this.add.rectangle(800,450,W,H,0x2e2a65,.16);header(this,'HOME BASE','Your journey to become a Food Ordering Master');
  panel(this,1195,147,700,120,0xffffff,.96,28,0xffffff);const lv=levelOf(this.save);[['MISSION',`${this.save.completed.length}/5`,'🎯'],['BADGES',`${this.save.badges.length}/5`,'🏅'],['LEVEL',`${lv}`,'⭐']].forEach((a,i)=>{const x=950+i*225;t(this,x,125,a[2]+' '+a[0],17,'#69708b');t(this,x,160,a[1],31,i===2?'#6d5dfc':'#253257')});
  panel(this,1200,226,690,34,0x33416a,.85,17,0xffffff);this.add.graphics().fillStyle(COLORS.yellow).fillRoundedRect(866,215,Math.max(22,668*this.save.completed.length/5),22,11);t(this,1200,228,`${this.save.completed.length*20}% Mission Progress`,15,'#ffffff');
  const y=makeYummy(this,260,450,1.15);t(this,260,680,'YUMMY',23,'#ffffff',{backgroundColor:'#6d5dfc',padding:{x:18,y:8}});
  panel(this,575,520,560,340,0xffffff,.97,34,0xe5e7ff);t(this,370,386,'Yummy says:',20,'#6d5dfc').setOrigin(0,.5);const msg="Hi there!\nI'm Yummy!\n\nLet's start our restaurant adventure!\n\nChoose a restaurant to begin your mission!";const dialog=t(this,575,535,'',25,'#253257',{align:'left',wordWrap:{width:480},lineSpacing:7}).setOrigin(.5);let n=0;this.time.addEvent({delay:22,repeat:msg.length-1,callback:()=>dialog.setText(msg.slice(0,++n))});
  panel(this,1195,510,700,500,0xf8fbff,.96,34,0xffffff);t(this,880,300,'RESTAURANT MISSIONS',28,'#253257').setOrigin(0,.5);restaurants.forEach((r,i)=>{const unlocked=i<=this.save.completed.length,done=this.save.completed.includes(i),x=1010+(i%2)*330,y=380+Math.floor(i/2)*118;const c=button(this,x,y,300,90,`${r.short}${done?'  ✓':''}`,unlocked?r.color:0x9ba2b9,()=>unlocked?transition(this,'Mission',{index:i}):null,r.icon);if(!unlocked)c.setAlpha(.74);if(i===4)c.setX(1175)});button(this,1195,700,460,64,'Explore Mission Map',COLORS.purple,()=>transition(this,'Map'),'🗺');
  bottomNav(this,'home');}}

class MapScene extends Base{constructor(){super('Map')}create(){super.create();this.add.image(800,450,'town').setDisplaySize(W,H);this.add.rectangle(800,450,W,H,0x27325d,.12);header(this,'MISSION MAP','Follow the path and complete every restaurant quest');const positions=[[320,430],[610,295],[885,355],[1130,260],[1320,500]];const g=this.add.graphics().lineStyle(14,0xffffff,.75);g.beginPath().moveTo(...positions[0]);positions.slice(1).forEach(p=>g.lineTo(...p));g.strokePath();positions.forEach((p,i)=>{const unlocked=i<=this.save.completed.length,done=this.save.completed.includes(i);const ring=this.add.circle(p[0],p[1],70,unlocked?restaurants[i].color:0x727b91,.95).setStrokeStyle(7,done?COLORS.yellow:0xffffff);t(this,p[0],p[1]-5,restaurants[i].icon,50);t(this,p[0],p[1]+92,restaurants[i].short,19,'#ffffff',{backgroundColor:'#29245d',padding:{x:12,y:6}});ring.setInteractive({useHandCursor:true}).on('pointerdown',()=>unlocked&&transition(this,'Mission',{index:i}));if(!unlocked)t(this,p[0],p[1],'🔒',33,'#ffffff')});const hero=makeYummy(this,positions[Math.min(this.save.completed.length,4)][0]-100,positions[Math.min(this.save.completed.length,4)][1]+80,.5);this.tweens.add({targets:hero,x:hero.x+45,duration:900,yoyo:true,repeat:-1});panel(this,800,730,940,110,0xffffff,.94,28,0xffffff);const d=daily[new Date().getDay()%daily.length];t(this,800,706,'☀️ DAILY CHALLENGE',18,'#6d5dfc');t(this,800,744,d,27,'#253257');bottomNav(this,'map')}}

class Mission extends Base{constructor(){super('Mission')}init(data){this.idx=data.index??0;this.stage=data.stage??1;this.choice=data.choice||null}create(){super.create();this.r=restaurants[this.idx];this.add.image(800,450,'town').setDisplaySize(W,H).setTint(this.r.color);this.add.rectangle(800,450,W,H,0x272451,.35);header(this,this.r.name,`QUEST ${this.idx+1}  •  Stage ${this.stage} of 6`);this.drawSteps();this.drawClerk();this.renderStage();}
 drawSteps(){for(let i=1;i<=6;i++){const x=500+(i-1)*135;this.add.circle(x,124,23,i<=this.stage?COLORS.yellow:0xffffff,i<=this.stage?1:.5);t(this,x,124,String(i),17,i<=this.stage?'#253257':'#6f7690');if(i<6)this.add.rectangle(x+68,124,80,7,i<this.stage?COLORS.yellow:0xffffff,i<this.stage?1:.4)}t(this,360,124,'MISSION',18,'#ffffff')}
 drawClerk(){panel(this,250,500,340,620,0xffffff,.94,34,0xffffff);const c=makeYummy(this,250,430,.83);t(this,250,677,`CLERK ${this.r.clerk.toUpperCase()}`,18,'#ffffff',{backgroundColor:'#27325d',padding:{x:14,y:8}})}
 talk(message){panel(this,940,275,980,190,0xffffff,.97,34,0xe8eaff);const txt=t(this,940,275,message,30,'#253257',{wordWrap:{width:850},lineSpacing:8});return txt}
 next(stage,extra={}){transition(this,'Mission',{index:this.idx,stage,...extra})}
 renderStage(){if(this.stage===1){this.talk(`Hello!\nWelcome to ${this.r.name}!`);button(this,940,610,380,76,'Say Hello!',this.r.color,()=>this.next(2),'👋');t(this,940,690,'Quest tip: Friendly greetings make a great start.',20,'#ffffff')}
  if(this.stage===2){this.talk('What would you like today?\nChoose one menu item.');this.r.menu.forEach((m,i)=>{const x=600+(i%3)*320,y=455+Math.floor(i/3)*175;const c=button(this,x,y,280,140,`${m[0]}\n$${m[1]}`,this.r.color,()=>this.next(3,{choice:i}),m[2]);c.getAt(2).setFontSize(22)})}
  if(this.stage===3){this.choice=this.choice??0;const item=this.r.menu[this.choice];const target=`I would like a ${item[0].toLowerCase()}.`;this.talk(`Your turn!\n“${target}”`);panel(this,940,500,850,130,0xffffff,.92,26,0xffffff);const transcript=t(this,940,475,'Type or use the microphone…',23,'#7b8197');button(this,780,590,280,72,'Type Answer',0x53607f,()=>this.typeAnswer(target,transcript,()=>this.next(4,{choice:this.choice})),'⌨');button(this,1100,590,280,72,'Speak',COLORS.coral,()=>this.listen(target,transcript,()=>this.next(4,{choice:this.choice})),'🎙');t(this,940,690,'Pronunciation: green = Excellent • yellow = Good • red = Try Again',17,'#ffffff')}
  if(this.stage===4){const item=this.r.menu[this.choice??0];this.talk(`You would like a ${item[0].toLowerCase()}.\nIs that correct?`);button(this,790,560,260,80,'Yes',COLORS.mint,()=>{sound('correct');this.next(5,{choice:this.choice})},'✓');button(this,1090,560,260,80,'No',COLORS.coral,()=>this.next(2),'✕')}
  if(this.stage===5){const item=this.r.menu[this.choice??0];this.talk(`That is ${item[1]} dollars.\n\nHow much is the ${item[0].toLowerCase()}?`);[item[1],item[1]+10,Math.max(5,item[1]-15)].sort(()=>Math.random()-.5).forEach((price,i)=>button(this,650+i*290,575,240,78,`${price} dollars`,price===item[1]?COLORS.mint:0x66708c,()=>price===item[1]?this.next(6,{choice:this.choice}):(sound('wrong'),this.cameras.main.shake(140,.008)),'💰'))}
  if(this.stage===6){this.completeMission()}}
 feedback(ans,target,label,done){const clean=s=>s.toLowerCase().replace(/[^a-z0-9 ]/g,'').trim();const a=clean(ans),b=clean(target);let score=0;if(a===b)score=1;else{const words=b.split(' ');score=words.filter(w=>a.includes(w)).length/words.length}const col=score>.85?'#28b989':score>.55?'#d79b00':'#e7505d';label.setText(`${score>.85?'Excellent!':score>.55?'Good!':'Try Again!'}\n${ans}`).setColor(col);sound(score>.55?'correct':'wrong');if(score>.55)this.time.delayedCall(900,done)}
 typeAnswer(target,label,done){const layer=document.getElementById('answer-layer'),form=document.getElementById('answer-form'),input=document.getElementById('answer-input');document.getElementById('answer-target').textContent=`Try: “${target}”`;input.value='';form.style.pointerEvents='auto';this.input.enabled=false;layer.classList.add('show');setTimeout(()=>input.focus(),50);document.getElementById('cancel-answer').onclick=()=>{layer.classList.remove('show');this.input.enabled=true};form.onsubmit=e=>{e.preventDefault();e.stopPropagation();const ans=input.value.trim();if(!ans){input.focus();return}form.style.pointerEvents='none';label.setText(ans);this.feedback(ans,target,label,done);setTimeout(()=>{layer.classList.remove('show');form.style.pointerEvents='auto'},1200)}}
 listen(target,label,done){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){label.setText('Speech recognition is not supported here.\nPlease use Type Answer.').setColor('#e7505d');return}const rec=new SR();rec.lang='en-US';rec.interimResults=true;const layer=document.getElementById('speech-layer'),live=document.getElementById('live-transcript');layer.classList.add('show');rec.onresult=e=>{let out='';for(let i=e.resultIndex;i<e.results.length;i++)out+=e.results[i][0].transcript;live.textContent=out;label.setText(out);if(e.results[e.results.length-1].isFinal){layer.classList.remove('show');this.feedback(out,target,label,done)}};rec.onerror=()=>{layer.classList.remove('show');label.setText('I could not hear that. Try again!').setColor('#e7505d')};rec.onend=()=>layer.classList.remove('show');document.getElementById('stop-listening').onclick=()=>rec.stop();rec.start()}
 completeMission(){const fresh=!this.save.completed.includes(this.idx);if(fresh){this.save.completed.push(this.idx);this.save.badges.push(this.r.badge);this.save.xp+=100;saveData(this.save);sound('badge')}const stars=[];for(let i=0;i<34;i++){const s=t(this,800,390,'✦',Phaser.Math.Between(18,38),['#ffd95a','#ffffff','#64d8b0','#ff7c7c'][i%4]);stars.push(s);this.tweens.add({targets:s,x:Phaser.Math.Between(430,1450),y:Phaser.Math.Between(120,760),alpha:0,scale:2,duration:Phaser.Math.Between(700,1500),delay:i*20})}panel(this,940,435,850,430,0xffffff,.97,38,COLORS.yellow);t(this,940,300,'MISSION COMPLETE!',42,'#6d5dfc');t(this,940,390,this.r.icon,92);t(this,940,478,`Badge unlocked: ${this.r.badge}`,28,'#253257');t(this,940,530,`+100 XP  •  Level ${levelOf(this.save)} ${levels[levelOf(this.save)-1]}`,20,'#69708b');button(this,940,630,390,76,this.idx===4?'View Achievements':'Continue Adventure',COLORS.purple,()=>transition(this,this.idx===4?'Achievements':'Home'),'✨')}
}

class Achievements extends Base{constructor(){super('Achievements')}create(){super.create();this.add.rectangle(800,450,W,H,0x6155d8);for(let i=0;i<20;i++)t(this,Phaser.Math.Between(0,W),Phaser.Math.Between(80,H-80),'✦',Phaser.Math.Between(14,34),'#8d82ef').setAlpha(.45);header(this,'BADGE GALLERY','Every mission leaves a little sparkle');t(this,800,170,`${this.save.badges.length} / 5 BADGES COLLECTED`,26,'#ffffff');restaurants.forEach((r,i)=>{const owned=this.save.badges.includes(r.badge),x=320+i*240;panel(this,x,410,210,330,owned?0xffffff:0xa7a5c5,owned?.98:.55,34,0xffffff);t(this,x,330,owned?r.icon:'?',75,owned?'#253257':'#ffffff');t(this,x,440,r.badge,23,owned?'#253257':'#ffffff',{wordWrap:{width:170}});t(this,x,520,owned?'UNLOCKED':'LOCKED',16,owned?'#28a77b':'#ffffff')});const lv=levelOf(this.save);panel(this,800,670,780,100,0xffffff,.95,28,0xffffff);t(this,550,650,`LEVEL ${lv}`,18,'#6d5dfc');t(this,550,682,levels[lv-1],27,'#253257');t(this,980,665,`${this.save.xp} XP`,29,'#6d5dfc');bottomNav(this,'badges')}}
class Leaderboard extends Base{constructor(){super('Leaderboard')}create(){super.create();this.add.rectangle(800,450,W,H,0x32b99b);header(this,'CLASS LEADERBOARD','A friendly practice board — keep climbing!');const names=[['1','Vocabulary Vicky','520'],['2','Sentence Sam','430'],['3','Brave Bella','360'],['4','You',String(this.save.xp)],['5','Hungry Henry','180']];panel(this,800,470,900,610,0xffffff,.97,38,0xffffff);names.forEach((row,i)=>{const y=240+i*92;if(row[1]==='You')this.add.rectangle(800,y,820,76,COLORS.yellow,.45);t(this,450,y,row[0],30,i<3?'#ff8b3d':'#6d5dfc');t(this,580,y,row[1],25,'#253257').setOrigin(0,.5);t(this,1110,y,row[2]+' XP',23,'#6d5dfc')});t(this,800,735,'Practice every day — progress matters more than rank!',20,'#65708e');bottomNav(this,'rank')}}

const config={type:Phaser.AUTO,parent:'game',width:W,height:H,backgroundColor:'#29245d',scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},render:{antialias:true,pixelArt:false},scene:[Boot,Home,MapScene,Mission,Achievements,Leaderboard]};
new Phaser.Game(config);
